services:
  postgres:
    container_name: healthmanager-postgres
    image: postgres
    environment:
      POSTGRES_USER: tds
      POSTGRES_PASSWORD: healthy
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - healthmanager-postgresnetwork
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5052:80"
    networks:
      - healthmanager-postgresnetwork
    restart: unless-stopped

networks:
  healthmanager-postgresnetwork:
    driver: bridge

volumes:
  postgres:
  pgadmin: