server:
  port: 8082

spring:
  application:
    name: mealtracker
#  datasource:
#    url: jdbc:postgresql://localhost:5432/mealtracker
#    username: tds
#    password: healthy
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#    show-sql: true
  datasource:
    url: jdbc:postgresql://postgres-mealtracker:5432/mealtrackerdb # port is 5432 since we're using the container name 'postgres-mealtracker' which is known and registered with the network healthmanager-postgresnetwork
    username: tds
    password: healthy
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  zipkin:
    base-url: http://healthmanager-zipkin:9411

eureka:
  client:
    service-url:
      defaultZone: http://healthmanager-eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
