server:
  port: 8084

spring:
  application:
    name: waterintaketracker
  datasource:
    url: jdbc:postgresql://postgres-waterintaketracker:5432/waterintaketrackerdb # port is 5432 since we're using the container name 'postgres-waterintaketracker' which is known and registered with the network healthmanager-postgresnetwork
    username: tds
    password: healthy
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  zipkin:
    base-url: http://healthmanager-zipkin:9411

eureka:
  client:
    service-url:
      defaultZone: http://healthmanager-eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true