server:
  port: 8082

spring:
  application:
    name: bowelmovement
  datasource:
    url: jdbc:postgresql://localhost:5433/bowelmovement
    username: tds
    password: healthy
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'